"""edição de estrutura da tabela

Revision ID: ae8bfff9e8b1
Revises: 18c804316de7
Create Date: 2025-01-01 17:20:48.750462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8bfff9e8b1'
down_revision = '18c804316de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instituicao_bancaria', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('descricao', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('tipo_conta', sa.String(length=50), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.drop_column('tipo_conta')
        batch_op.drop_column('descricao')
        batch_op.drop_column('instituicao_bancaria')

    # ### end Alembic commands ###
