"""tabela transacoes

Revision ID: dc875626e776
Revises: ae8bfff9e8b1
Create Date: 2025-01-03 15:44:09.250437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc875626e776'
down_revision = 'ae8bfff9e8b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('natureza', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacoes')
    # ### end Alembic commands ###
